# Generated by Django 3.0.8 on 2020-08-20 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=8)),
                ('location_type', models.CharField(choices=[('ORDER', 'Order'), ('ITEM', 'Item')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=12)),
                ('wave', models.CharField(max_length=13)),
                ('pick_sequence', models.CharField(max_length=13)),
                ('closed', models.DateTimeField(blank=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=13)),
                ('coo', models.CharField(blank=True, max_length=2)),
                ('po', models.CharField(blank=True, max_length=6)),
                ('season', models.CharField(blank=True, max_length=6)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Location')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.OrderHeader')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=13)),
                ('coo', models.CharField(max_length=2)),
                ('po', models.CharField(max_length=6)),
                ('season', models.CharField(max_length=6)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('taken', models.DateTimeField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Location')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_by', to=settings.AUTH_USER_MODEL)),
                ('taken_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.OrderLine')),
            ],
        ),
    ]
