# Generated by Django 3.0.8 on 2020-08-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20200820_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='location',
        ),
        migrations.AddField(
            model_name='orderheader',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Location'),
        ),
    ]
