# Generated by Django 3.0.8 on 2020-08-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20200820_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderheader',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterField(
            model_name='item',
            name='taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Location'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hospital.OrderHeader'),
        ),
    ]
