# Generated by Django 3.0.8 on 2020-08-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20200820_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderheader',
            name='removed_at',
        ),
        migrations.RemoveField(
            model_name='orderheader',
            name='removed_by',
        ),
        migrations.AlterField(
            model_name='item',
            name='taken_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_to', to='hospital.OrderLine'),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Location'),
        ),
    ]
