# Generated by Django 3.0.8 on 2020-08-07 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('station_type', models.CharField(max_length=4)),
                ('previous', models.IntegerField()),
                ('current', models.IntegerField()),
                ('estimated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
                ('is_measurable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=1)),
                ('number', models.CharField(max_length=3)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='callup.StationType')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateTimeField(auto_now_add=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('logout_type', models.CharField(blank=True, choices=[('M', 'MANUAL'), ('F', 'FORCED')], max_length=1, null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='callup.Station')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_station_report', 'Can view station report'),),
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=50)),
                ('station_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='callup.StationType')),
            ],
        ),
        migrations.CreateModel(
            name='IssueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('issue_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='callup.IssueType')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='callup.Station')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_supervisor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_resolve_issue', 'Can resolve issue'), ('can_view_issue_report', 'Can view issue report')),
            },
        ),
    ]
